#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

if [ ! -d "KubeSec-master/bandit_scanning" ]
then
	mkdir "KubeSec-Master/bandit_scanning"
fi
bandit -r -f csv -o "KubeSec-Master/bandit_scanning/results.csv" .
exit 0
